# Generated by Django 6.0.5 on 2026-05-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(default='M15', max_length=50)),
                ('hero_title', models.CharField(default='M15 Creative Agency', max_length=100)),
                ('hero_subtitle', models.CharField(default='We build modern websites and digital experiences.', max_length=200)),
                ('about_text', models.TextField(blank=True)),
                ('copyright_text', models.CharField(default='© 2026 M15 Agency. All rights reserved.', max_length=150)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Content',
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('github', 'GitHub')], max_length=20)),
                ('url', models.URLField()),
                ('icon', models.CharField(default='bi-link-45deg', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
