# Generated by Django 6.0.5 on 2026-05-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload your agency logo (PNG/SVG recommended)', null=True, upload_to='site/logo/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='motto',
            field=models.CharField(default='We Code You Grow', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(default='We Code You Grow', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='M15', max_length=100),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon',
            field=models.CharField(default='bi-link-45deg', help_text="Bootstrap Icon class, e.g., 'instagram', 'tiktok'", max_length=30),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('twitter', 'Twitter/X')], max_length=20),
        ),
    ]
